apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: env-secret-backend
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: env-secret-backend
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY
      remoteRef:
        key: env-secret-backend
        property: AWS_ACCESS_KEY
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: env-secret-backend
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: REGION
      remoteRef:
        key: env-secret-backend
        property: REGION
    - secretKey: BUCKET_NAME
      remoteRef:
        key: env-secret-backend
        property: BUCKET_NAME
    - secretKey: AWS_COGNITO_USER_POOL_ID
      remoteRef:
        key: env-secret-backend
        property: AWS_COGNITO_USER_POOL_ID
    - secretKey: AWS_COGNITO_APP_CLIENT_ID
      remoteRef:
        key: env-secret-backend
        property: AWS_COGNITO_APP_CLIENT_ID
    - secretKey: OIDC_KAKAO_CLIENT_SECRET
      remoteRef:
        key: env-secret-backend
        property: OIDC_KAKAO_CLIENT_SECRET
    - secretKey: REDIRECT_URI
      remoteRef:
        key: env-secret-backend
        property: REDIRECT_URI
    - secretKey: TOKEN_URL
      remoteRef:
        key: env-secret-backend
        property: TOKEN_URL
    - secretKey: DATABASE_URL
      remoteRef:
        key: env-secret-backend
        property: DATABASE_URL
    - secretKey: DB_HOST
      remoteRef:
        key: env-secret-backend
        property: DB_HOST
    - secretKey: MYSQL_USER
      remoteRef:
        key: env-secret-backend
        property: MYSQL_USER
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: env-secret-backend
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: env-secret-backend
        property: MYSQL_DATABASE
    - secretKey: MYSQL_PORT
      remoteRef:
        key: env-secret-backend
        property: MYSQL_PORT
    - secretKey: FRONT_URL
      remoteRef:
        key: env-secret-backend
        property: FRONT_URL
    - secretKey: CERTIFICATE_ARN
      remoteRef:
        key: env-secret-backend
        property: CERTIFICATE_ARN
